```{r}
library(MASS)
attach(Boston)
lm.fit=lm(medv~lstat)
```

```{r}
summary(lm.fit)
```
```{r}
names(lm.fit)
```
```{r}
coef(lm.fit)
```
```{r}
confint(lm.fit)
```
```{r}
predict(lm.fit,data.frame(lstat=c(5,10,15)),interval="confidence")
```
```{r}
predict(lm.fit,data.frame(lstat=c(5,10,15)),interval="prediction")
#As expected, the confidence and prediction intervals are centered around the same point, but the latter is much wider
```
```{r}
plot(lstat,medv)
abline(lm.fit)
```
```{r}
par(mfrow=c(2,2))
plot(lm.fit)
```
```{r}
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
```
```{r}
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```
```{r}
lm.fit=lm(medv~lstat+age)
summary(lm.fit)
```
```{r}
lm.fit=lm(medv~., data=Boston)
summary(lm.fit)
```
```{r}
summary(lm.fit)$r.sq
summary(lm.fit)$sigma
```
```{r}
library(car)
vif(lm.fit)
```
```{r}
summary(lm(medv~lstat*age))
```
```{r}
lm.fit2=lm(medv~lstat+I(lstat^2))
summary(lm.fit2)
```
```{r}
lm.fit=lm(medv~lstat)
anova(lm.fit,lm.fit2)
```
```{r}
par(mfrow=c(2,2))
plot(lm.fit2)
```
```{r}
lm.fit5=lm(medv~poly(lstat,5))
summary(lm.fit5)
```

